image: docker/compose:latest

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

stages:
    - build

services:
  - docker:dind

before_script:
  - docker info
  - docker-compose --version
 
build:
    only: 
      - development
    stage: build
    script:
        - docker-compose -f docker-compose.prod.yml up -d --build