image: docker/compose:latest

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

stages:
    - build

services:
  - docker:dind
 
build:
    only: 
      - master
    stage: build
    tags:
      - iit
      - prod
    script:
        - docker build -t app/mission-klima .
        - docker run -d -p 3000:3000  --rm --name klima app/mission-klima