image: docker/compose:latest

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

stages:
    - build

services:
  - docker:dind
 
build:
    only: 
      - master
    stage: build
    script:
        - docker build -t app/mission-klima .  
        - docker run -d -p 5000:3000 --rm --name klima app/mission-klima