image: docker/compose:latest

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - build

services:
  - docker:dind

before_script:
  - docker info
  - docker-compose --version
 
build:
    only: 
    - master
    stage: build
    tags:
      - iit
      - prod
    script:
        - docker-compose --version
        - docker-compose up -d --build
