image: docker/compose:latest

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

stages:
    - build

services:
  - docker:dind
 
build:
    only: 
      - master
    stage: build
    script:
        - Dockerfile up -d --build