image: docker

services:
  - docker:dind

stages:
  - build
 
build:
    only: 
      - master
    stage: build
    tags:
      - iit
      - prod
    script:
        - docker build -t app/mission-klima .
        - docker run -d -p 3000:3000  --rm --name klima app/mission-klima