version: '3.7'
services:
  react:
    stdin_open: true 
    tty: true
    container_name: react_prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true